#!/usr/bin/env python3
"""strings.tsv -> common/strings_data.cpp.

The TSV has a header row naming the columns (key, then language codes in
the order common/i18n.cpp lists them after English) and one row per
English string. An empty cell falls back to English at run time. "\\n" in
a cell is a newline. Every %-directive in the key must appear in each
translation in the same order, or this refuses to generate.
"""
import re, sys, os
root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
src = os.path.join(root, 'common', 'strings.tsv')
dst = os.path.join(root, 'common', 'strings_data.cpp')
LANGS = ['fr', 'es', 'it', 'ja', 'ko']
DIRECTIVE = re.compile(r'%[-+ #0-9.*]*(?:ll|l|j|z|h)?[a-zA-Z%]')

def cpp(s):
    out = ''
    for ch in s:
        if ch == '\\': out += '\\\\'
        elif ch == '"': out += '\\"'
        elif ch == '\n': out += '\\n'
        elif ord(ch) < 0x20: out += '\\x%02x' % ord(ch)
        else: out += ch
    return '"' + out + '"'

rows = []
with open(src, encoding='utf-8') as f:
    header = f.readline().rstrip('\n').split('\t')
    assert header[0] == 'key' and header[1:] == LANGS, header
    seen = set()
    for n, line in enumerate(f, 2):
        line = line.rstrip('\n')
        if not line or line.startswith('#'): continue
        cells = line.split('\t')
        cells += [''] * (len(header) - len(cells))
        key = cells[0].replace('\\n', '\n')
        if key in seen:
            sys.exit(f'{src}:{n}: duplicate key {key!r}')
        seen.add(key)
        want = DIRECTIVE.findall(key)
        texts = []
        for code, cell in zip(LANGS, cells[1:1+len(LANGS)]):
            cell = cell.replace('\\n', '\n')
            if cell and DIRECTIVE.findall(cell) != want:
                sys.exit(f'{src}:{n}: {code}: format directives differ from the key: {cell!r}')
            texts.append(cell)
        rows.append((key, texts))

with open(dst, 'w', encoding='utf-8') as out:
    out.write('// Generated by tools/gen_strings.py from common/strings.tsv. Do not edit.\n')
    out.write('#include <cstddef>\n\nnamespace xlive::i18n {\n\n')
    out.write('struct Row {\n    const char* key;\n    const char* text[%d];\n};\n\n' % len(LANGS))
    out.write('extern const Row kRows[] = {\n')
    for key, texts in rows:
        out.write('    {%s, {%s}},\n' % (cpp(key), ', '.join(cpp(t) if t else 'nullptr' for t in texts)))
    out.write('};\nextern const size_t kRowCount = sizeof(kRows) / sizeof(kRows[0]);\n\n}  // namespace xlive::i18n\n')
print(f'{len(rows)} strings -> {os.path.relpath(dst, root)}')
