#!/usr/bin/env python3
"""Subsets Noto Sans CJK to the glyphs the launcher draws in Japanese and
Korean and writes thirdparty/notocjk/{NotoSansCJK-subset.otf,notocjk_data.cpp}.

The full font is 16 MB; the subset — every character in strings.tsv's ja
and ko columns, the kana, the compatibility jamo, CJK punctuation and
the fullwidth forms — is a few hundred KB, and lives in the binary like
Selawik does, so a Japanese or Korean launcher needs nothing installed.
A friend's message in Korean can still reach a syllable outside it; the
system's CJK font, when there is one, is merged behind for those.

Run after editing strings.tsv. Needs fonttools (pyftsubset). The full font
is fetched once into thirdparty/notocjk/.cache/ and hash-checked.
"""
import hashlib, os, pathlib, subprocess, sys, urllib.request

root = pathlib.Path(__file__).resolve().parent.parent
out_dir = root / 'thirdparty' / 'notocjk'
cache = out_dir / '.cache'
full = cache / 'NotoSansCJKjp-Regular.otf'
URL = 'https://github.com/notofonts/noto-cjk/raw/main/Sans/OTF/Japanese/NotoSansCJKjp-Regular.otf'
SHA256 = '68a3fc98800b2a27b371f2fb79991daf3633bd89309d4ffaa6946fd587f375b5'
LICENSE_URL = 'https://raw.githubusercontent.com/notofonts/noto-cjk/main/Sans/LICENSE'

cache.mkdir(parents=True, exist_ok=True)
if not full.exists():
    print('fetching', URL)
    urllib.request.urlretrieve(URL, full)
digest = hashlib.sha256(full.read_bytes()).hexdigest()
if digest != SHA256:
    sys.exit(f'{full}: sha256 {digest}, expected {SHA256}')
if not (out_dir / 'LICENSE.txt').exists():
    urllib.request.urlretrieve(LICENSE_URL, out_dir / 'LICENSE.txt')

# The characters: everything non-ASCII in the ja and ko columns.
chars = set()
with open(root / 'common' / 'strings.tsv', encoding='utf-8') as f:
    header = f.readline().rstrip('\n').split('\t')
    cols = [header.index('ja'), header.index('ko')]
    for line in f:
        cells = line.rstrip('\n').split('\t')
        for c in cols:
            if c < len(cells):
                chars.update(ch for ch in cells[c] if ord(ch) > 0x7F)
chars.update(ch for ch in '日本語한국어')
text_file = cache / 'chars.txt'
text_file.write_text(''.join(sorted(chars)), encoding='utf-8')

subset = out_dir / 'NotoSansCJK-subset.otf'
subprocess.check_call([
    'pyftsubset', str(full), f'--text-file={text_file}',
    '--unicodes=U+3000-303F,U+3041-3096,U+30A1-30FA,U+30FC,U+3131-3163,U+FF01-FF60,U+00A0-00FF',
    '--layout-features=', '--no-hinting', '--desubroutinize', '--name-IDs=1,2,6',
    f'--output-file={subset}',
])
data = subset.read_bytes()
out = ['// Generated by tools/gen_cjk_font.py: Noto Sans CJK JP Regular (SIL OFL 1.1, see',
       '// LICENSE.txt beside it), subset to the glyphs the launcher draws in Japanese',
       '// and Korean. Regenerate after editing common/strings.tsv.',
       '#include "notocjk.h"', '', 'namespace notocjk {', '',
       f'const unsigned int kSubsetSize = {len(data)};',
       f'const unsigned char kSubset[{len(data)}] = {{']
for i in range(0, len(data), 24):
    out.append('    ' + ','.join(str(b) for b in data[i:i+24]) + ',')
out += ['};', '', '}  // namespace notocjk', '']
(out_dir / 'notocjk_data.cpp').write_text('\n'.join(out))
(out_dir / 'notocjk.h').write_text('''// Noto Sans CJK (SIL OFL 1.1), subset to the launcher's Japanese and Korean
// strings by tools/gen_cjk_font.py, as bytes for AddFontFromMemoryTTF with
// FontDataOwnedByAtlas off.
#pragma once

namespace notocjk {

extern const unsigned char kSubset[];
extern const unsigned int kSubsetSize;

}  // namespace notocjk
''')
print(f'{len(chars)} characters -> {subset.name}: {len(data)} bytes')
